import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    tLr: {
        position: "absolute",
        top: 0,
        left: 0,
        width: 50,
        height: 5,
        borderRadius: 5,
    },
    tLb: {
        position: "absolute",
        top: 0,
        left: 0,
        width: 5,
        height: 50,
        borderRadius: 5,
    },
    tRl: {
        position: "absolute",
        top: 0,
        right: 0,
        width: 50,
        height: 5,
        borderRadius: 5,
    },
    tRb: {
        position: "absolute",
        top: 0,
        right: 0,
        width: 5,
        height: 50,
        borderRadius: 5,
    },
    bLt: {
        position: "absolute",
        bottom: 0,
        left: 0,
        width: 50,
        height: 5,
        borderRadius: 5,
    },
    bLr: {
        position: "absolute",
        bottom: 0,
        left: 0,
        width: 5,
        height: 50,
        borderRadius: 5,
    },
    bRl: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 50,
        height: 5,
        borderRadius: 5,
    },
    bRt: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 5,
        height: 50,
        borderRadius: 5,
    },
});
